version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_USER=raibruh
      - DATABASE_PASSWORD=Rai123
      - POSTGRES_DB=gpti
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PORT=8080
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: raibruh
      POSTGRES_PASSWORD: Rai123
      POSTGRES_DB: gpti
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
